// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: comunicacion.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Comunicacion_EnviarEntrenadores_FullMethodName  = "/comunicacion.Comunicacion/EnviarEntrenadores"
	Comunicacion_EnviarTorneos_FullMethodName       = "/comunicacion.Comunicacion/EnviarTorneos"
	Comunicacion_InscribirEntrenador_FullMethodName = "/comunicacion.Comunicacion/InscribirEntrenador"
	Comunicacion_AsignarCombate_FullMethodName      = "/comunicacion.Comunicacion/AsignarCombate"
	Comunicacion_ConsultarEntrenador_FullMethodName = "/comunicacion.Comunicacion/ConsultarEntrenador"
)

// ComunicacionClient is the client API for Comunicacion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComunicacionClient interface {
	EnviarEntrenadores(ctx context.Context, in *ListaEntrenadores, opts ...grpc.CallOption) (*Respuesta, error)
	EnviarTorneos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListaTorneos, error)
	InscribirEntrenador(ctx context.Context, in *InscribirRequest, opts ...grpc.CallOption) (*InscribirResponse, error)
	AsignarCombate(ctx context.Context, in *Combate, opts ...grpc.CallOption) (*Respuesta, error)
	ConsultarEntrenador(ctx context.Context, in *EntrenadorID, opts ...grpc.CallOption) (*Entrenador, error)
}

type comunicacionClient struct {
	cc grpc.ClientConnInterface
}

func NewComunicacionClient(cc grpc.ClientConnInterface) ComunicacionClient {
	return &comunicacionClient{cc}
}

func (c *comunicacionClient) EnviarEntrenadores(ctx context.Context, in *ListaEntrenadores, opts ...grpc.CallOption) (*Respuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, Comunicacion_EnviarEntrenadores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comunicacionClient) EnviarTorneos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListaTorneos, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaTorneos)
	err := c.cc.Invoke(ctx, Comunicacion_EnviarTorneos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comunicacionClient) InscribirEntrenador(ctx context.Context, in *InscribirRequest, opts ...grpc.CallOption) (*InscribirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InscribirResponse)
	err := c.cc.Invoke(ctx, Comunicacion_InscribirEntrenador_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comunicacionClient) AsignarCombate(ctx context.Context, in *Combate, opts ...grpc.CallOption) (*Respuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, Comunicacion_AsignarCombate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comunicacionClient) ConsultarEntrenador(ctx context.Context, in *EntrenadorID, opts ...grpc.CallOption) (*Entrenador, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Entrenador)
	err := c.cc.Invoke(ctx, Comunicacion_ConsultarEntrenador_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComunicacionServer is the server API for Comunicacion service.
// All implementations must embed UnimplementedComunicacionServer
// for forward compatibility.
type ComunicacionServer interface {
	EnviarEntrenadores(context.Context, *ListaEntrenadores) (*Respuesta, error)
	EnviarTorneos(context.Context, *Empty) (*ListaTorneos, error)
	InscribirEntrenador(context.Context, *InscribirRequest) (*InscribirResponse, error)
	AsignarCombate(context.Context, *Combate) (*Respuesta, error)
	ConsultarEntrenador(context.Context, *EntrenadorID) (*Entrenador, error)
	mustEmbedUnimplementedComunicacionServer()
}

// UnimplementedComunicacionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComunicacionServer struct{}

func (UnimplementedComunicacionServer) EnviarEntrenadores(context.Context, *ListaEntrenadores) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarEntrenadores not implemented")
}
func (UnimplementedComunicacionServer) EnviarTorneos(context.Context, *Empty) (*ListaTorneos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarTorneos not implemented")
}
func (UnimplementedComunicacionServer) InscribirEntrenador(context.Context, *InscribirRequest) (*InscribirResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InscribirEntrenador not implemented")
}
func (UnimplementedComunicacionServer) AsignarCombate(context.Context, *Combate) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AsignarCombate not implemented")
}
func (UnimplementedComunicacionServer) ConsultarEntrenador(context.Context, *EntrenadorID) (*Entrenador, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsultarEntrenador not implemented")
}
func (UnimplementedComunicacionServer) mustEmbedUnimplementedComunicacionServer() {}
func (UnimplementedComunicacionServer) testEmbeddedByValue()                      {}

// UnsafeComunicacionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComunicacionServer will
// result in compilation errors.
type UnsafeComunicacionServer interface {
	mustEmbedUnimplementedComunicacionServer()
}

func RegisterComunicacionServer(s grpc.ServiceRegistrar, srv ComunicacionServer) {
	// If the following call pancis, it indicates UnimplementedComunicacionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Comunicacion_ServiceDesc, srv)
}

func _Comunicacion_EnviarEntrenadores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListaEntrenadores)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComunicacionServer).EnviarEntrenadores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comunicacion_EnviarEntrenadores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComunicacionServer).EnviarEntrenadores(ctx, req.(*ListaEntrenadores))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comunicacion_EnviarTorneos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComunicacionServer).EnviarTorneos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comunicacion_EnviarTorneos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComunicacionServer).EnviarTorneos(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comunicacion_InscribirEntrenador_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InscribirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComunicacionServer).InscribirEntrenador(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comunicacion_InscribirEntrenador_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComunicacionServer).InscribirEntrenador(ctx, req.(*InscribirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comunicacion_AsignarCombate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Combate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComunicacionServer).AsignarCombate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comunicacion_AsignarCombate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComunicacionServer).AsignarCombate(ctx, req.(*Combate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comunicacion_ConsultarEntrenador_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntrenadorID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComunicacionServer).ConsultarEntrenador(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comunicacion_ConsultarEntrenador_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComunicacionServer).ConsultarEntrenador(ctx, req.(*EntrenadorID))
	}
	return interceptor(ctx, in, info, handler)
}

// Comunicacion_ServiceDesc is the grpc.ServiceDesc for Comunicacion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Comunicacion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comunicacion.Comunicacion",
	HandlerType: (*ComunicacionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnviarEntrenadores",
			Handler:    _Comunicacion_EnviarEntrenadores_Handler,
		},
		{
			MethodName: "EnviarTorneos",
			Handler:    _Comunicacion_EnviarTorneos_Handler,
		},
		{
			MethodName: "InscribirEntrenador",
			Handler:    _Comunicacion_InscribirEntrenador_Handler,
		},
		{
			MethodName: "AsignarCombate",
			Handler:    _Comunicacion_AsignarCombate_Handler,
		},
		{
			MethodName: "ConsultarEntrenador",
			Handler:    _Comunicacion_ConsultarEntrenador_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comunicacion.proto",
}
